### ISSUE TITLE
Bug - Failed to launch the browser process!

### ISSUE THREAD

**Issue by matthieubrau** [jontewks/heroku-buildpack-puppeteer-firefox#1] opened 2021-07-12 10:32 UTC
Hello @jontewks 

I'm using builpack-puppeteer-firefox on heroku and I have some problem

It's work fine after dyno restart, but after some successfull tries, the error appear.
The dyno memory seems to be ok.
I don't understand what happend

Thanks for your feedback

You can find the logs below (first logs are own console log to display launch browser options)

2021-07-12T09:36:37.342110+00:00 app[web.1]: -- Launch browser with options --
2021-07-12T09:36:37.342265+00:00 app[web.1]: {
2021-07-12T09:36:37.342266+00:00 app[web.1]:   product: 'firefox',
2021-07-12T09:36:37.342267+00:00 app[web.1]:   args: [
2021-07-12T09:36:37.342267+00:00 app[web.1]:     '--disable-extensions',
2021-07-12T09:36:37.342267+00:00 app[web.1]:     '--no-sandbox',
2021-07-12T09:36:37.342267+00:00 app[web.1]:     '--disable-setuid-sandbox'
2021-07-12T09:36:37.342268+00:00 app[web.1]:   ]
2021-07-12T09:36:37.342268+00:00 app[web.1]: }
2021-07-12T09:36:39.568656+00:00 app[web.1]: (node:21) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
2021-07-12T09:36:39.568664+00:00 app[web.1]: *** You are running in headless mode.
2021-07-12T09:36:39.568665+00:00 app[web.1]: JavaScript error: resource://gre/modules/PromiseWorker.jsm, line 189: NS_ERROR_UNEXPECTED
2021-07-12T09:36:39.568666+00:00 app[web.1]: 
2021-07-12T09:36:39.568666+00:00 app[web.1]: 
2021-07-12T09:36:39.568666+00:00 app[web.1]: TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
2021-07-12T09:36:39.568667+00:00 app[web.1]: 
2021-07-12T09:36:39.568667+00:00 app[web.1]:     at onClose (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:194:20)
2021-07-12T09:36:39.568690+00:00 app[web.1]:     at ChildProcess.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:79)
2021-07-12T09:36:39.568691+00:00 app[web.1]:     at ChildProcess.emit (events.js:387:35)
2021-07-12T09:36:39.568692+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
2021-07-12T09:36:39.568758+00:00 app[web.1]: (node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)

**Comment by jontewks** [comment] 2021-07-15 15:20
Hey @matthieubrau, would you mind posting the code you are running as well? Its odd that it would happen some of the time as this buildpack only installs the required libraries to get it running at all, so my best guess is something that is happening within the code running. The final message there requests wrapping things in a catch for any promise rejections, but that also may be something happening internally since it says it failed to even launch. No idea currently!

**Comment by matthieubrau** [comment] 2021-07-15 17:09
Hello @jontewks 

Here is my code :
```
const puppeteer = require("puppeteer")

const getContent = async (url, selector = null, product = 'firefox') => {
  const options = {
    product: product,
    args: [
      '--disable-extensions',
      '--no-sandbox',
      '--disable-setuid-sandbox'
   ]
  }
  console.log('-- Launch browser with options --');
  console.log(options);
  const browser = await promiseTimeout(10000, puppeteer.launch(options))
  page = await browser.newPage()
  await page.goto(url)
  await page.waitForSelector(selector)
  html = await page.content()
  await browser.close()
  return {content: html}
}

```

I add a timeoutpromise to wait browser.launch 10 secondes but the error raised after 1 seconde so it should not be a problem

This method is call throuth an api : 

```
const getPage = async (req,res) => {
  res.send(await getContent(req.query.url, req.query.selector, req.query.browser))
}
router.get('/page', scrapper.getPage)
```

Should I require puppeteer-firefox ?

Here is the complete code :
[puppeteer_api.zip](https://github.com/jontewks/heroku-buildpack-puppeteer-firefox/files/6825002/puppeteer_api.zip)

**Comment by jontewks** [comment] 2021-07-19 15:58
Well the promise timeout isn't actually working the way you are thinking, in order to delay the launch call for the 10 seconds, you'd have to have the following:
```js
const browser = await promiseTimeout(10000, () => puppeteer.launch(options))
```
Right now the launch is called right away and thats where the issue is stemming from. I still am not sure why though and googleing it doesn't come up with much at all. 

My two best guesses to at least get you unstuck would be to see if a previous version of puppeteer with a different firefox version works instead, or to wrap the whole thing in an intelligent try/catch block that will catch these errors and rerun the request, since its intermittently failing on you.

Also I'm not sure about that `promiseTimeout` since that isn't a built in function, but just be sure thats actually returning the value of the resolved promise so that it can be assigned to browser as well.

**Comment by matthieubrau** [comment] 2021-07-21 12:03
Hello @jontewks 
It seems better without promiseTimeout
I add try catch to close browser for some errors.
Before that update after a timeout error, the dyno raise always error, and I had to restart it
Now it could continue withour errors.

So it's much better, thanks for your advises
I will open other issues for other questions / problems
Thanks again

**Closed as completed** 2022-02-08 14:33 UTC
